# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

#env_files:
  # use only one or release will fail!
#  github_token: E:\Company\.goreleasertoken\gh_token

before:
  hooks:
    - go mod download
builds:
  - binary: goreleaser-app
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: .
    ldflags: -s -w -X github.com/zhouxianyou/goreleaser-app/cmd.version={{.Version}} -X github.com/zhouxianyou/goreleaser-app/cmd.commit={{.ShortCommit}} -X github.com/zhouxianyou/goreleaser-app/cmd.date={{.Date}}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

dockers:
  - dockerfile: ./Dockerfile
    binaries:
      - goreleaser-app
    image_templates:
      - "zhouxianyou/goreleaser-app:latest"
      - "zhouxianyou/goreleaser-app:{{ .Tag }}"
      - "zhouxianyou/goreleaser-app:v{{ .Major }}.{{ .Minor }}"