name: goreleaser

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-16.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.1.0
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1.0.0
        with:
          go-version: 1.13.x
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.ACTION_DEPLOY_KEY }}
