name: goreleaser

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Setup asc
        run: |
          /usr/bin/gpg --keyserver hkp://keyserver.ubuntu.com --receive-keys 1998F1B1867AC528
          /usr/bin/gpg -a --export 1998F1B1867AC528 > /home/runner/key.asc
          more /home/runner/key.asc
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.ACTION_DEPLOY_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}