name: goreleaser

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      -
        name: Run GoReleaser release
        uses: goreleaser/goreleaser-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.ACTION_DEPLOY_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
      -
        name: Run GoReleaser skip publish snapshot
        uses: goreleaser/goreleaser-action@v1
        if: startsWith(github.ref, 'refs/branches/master')
        with:
          version: latest
          args: release --skip-publish --rm-dist --snapshot
          key: ${{ secrets.ACTION_DEPLOY_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}