name: goreleaser

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.1.0
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1.0.0
        with:
          go-version: 1.13.x
      - name: Setup ssh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
           echo "Setup ssh"
#          mkdir -p ~/.ssh/
#          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#          sudo apt-get install ca-certificates
#          curl -sSL https://get.docker.io/gpg | sudo apt-key add -
          wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg
          sudo apt-key add sublimehq-pub.gpg
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1.3.1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.ACTION_DEPLOY_KEY }}
